// client/src/app/pages/group.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { ApiService } from '../api.service';

@Component({
  selector: 'app-group',
  imports: [FormsModule, RouterLink],
  template: `
    @if (group) {
      <div class="page">
        <p class="crumbs"><a routerLink="/groups">Groups</a><span>/</span><span>{{ group.name }}</span></p>
        <header class="page-head">
          <div>
            <h1>{{ group.name }}</h1>
            <p class="dek">{{ group.description || 'No description yet.' }}</p>
          </div>
        </header>
        <div class="cards">
          <section class="card stack">
            <h2>People</h2>
            @for (member of group.members_list; track member.id) {
              <p>{{ member.full_name }} <span class="muted">{{ member.email }}</span></p>
            }
            @if (api.canTeach()) {
              <form class="stack" (ngSubmit)="add()">
                <label class="field"><span>Add by email</span><input [(ngModel)]="email" name="email" type="email" required /></label>
                <button class="btn small" type="submit">Add</button>
              </form>
            }
          </section>
          <section class="card stack">
            <h2>Messages</h2>
            @for (item of group.posts; track item.id) {
              <article>
                <strong>{{ item.author_name }}</strong>
                <p>{{ item.body }}</p>
              </article>
            }
            @if (!group.posts.length) {
              <p class="muted">No messages in this group yet.</p>
            }
            <form class="news-form" (ngSubmit)="post()">
              <input [(ngModel)]="body" name="body" placeholder="Write a message" required />
              <button class="btn small" type="submit">Post</button>
            </form>
          </section>
        </div>
      </div>
    }
  `,
})
export class GroupComponent implements OnInit {
  api = inject(ApiService);
  route = inject(ActivatedRoute);
  group: any = null;
  email = '';
  body = '';

  ngOnInit() {
    this.load();
  }

  async load() {
    this.group = await this.api.api(`/groups/${this.route.snapshot.paramMap.get('id')}`);
  }

  async add() {
    try {
      this.group = await this.api.api(`/groups/${this.route.snapshot.paramMap.get('id')}/members`, { method: 'POST', body: { email: this.email } });
      this.email = '';
      this.api.toast('Added to the group.');
    } catch (error: any) {
      this.api.toast(error.message, 'warn');
    }
  }

  async post() {
    try {
      await this.api.api('/feed', { method: 'POST', body: { body: this.body, group_id: Number(this.route.snapshot.paramMap.get('id')) } });
      this.body = '';
      await this.load();
    } catch (error: any) {
      this.api.toast(error.message, 'warn');
    }
  }
}

// src/views/Group.vue
<script setup>
import { onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { api, canTeach, toast } from '../api'

const route = useRoute()
const group = ref(null)
const email = ref('')
const body = ref('')

async function load() {
  group.value = await api(`/groups/${route.params.id}`)
}
onMounted(load)

async function add() {
  try {
    group.value = await api(`/groups/${route.params.id}/members`, { method: 'POST', body: { email: email.value } })
    email.value = ''
    toast('Added to the group.')
  } catch (error) {
    toast(error.message, 'warn')
  }
}

async function post() {
  try {
    await api('/feed', { method: 'POST', body: { body: body.value, group_id: Number(route.params.id) } })
    body.value = ''
    await load()
  } catch (error) {
    toast(error.message, 'warn')
  }
}
</script>

<template>
  <div v-if="group" class="page">
    <p class="crumbs"><router-link to="/groups">Groups</router-link><span>/</span><span>{{ group.name }}</span></p>
    <header class="page-head">
      <div>
        <h1>{{ group.name }}</h1>
        <p class="dek">{{ group.description || 'No description yet.' }}</p>
      </div>
    </header>
    <div class="cards">
      <section class="card stack">
        <h2>People</h2>
        <p v-for="member in group.members_list" :key="member.id">{{ member.full_name }} <span class="muted">{{ member.email }}</span></p>
        <form v-if="canTeach()" class="stack" @submit.prevent="add">
          <label class="field"><span>Add by email</span><input v-model="email" type="email" required /></label>
          <button class="btn small" type="submit">Add</button>
        </form>
      </section>
      <section class="card stack">
        <h2>Messages</h2>
        <article v-for="item in group.posts" :key="item.id">
          <strong>{{ item.author_name }}</strong>
          <p>{{ item.body }}</p>
        </article>
        <p v-if="!group.posts.length" class="muted">No messages in this group yet.</p>
        <form class="news-form" @submit.prevent="post">
          <input v-model="body" placeholder="Write a message" required />
          <button class="btn small" type="submit">Post</button>
        </form>
      </section>
    </div>
  </div>
</template>
