// client/src/app/pages/search.component.ts
import { Component, DestroyRef, OnInit, inject } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { ApiService } from '../api.service';

@Component({
  selector: 'app-search',
  imports: [RouterLink],
  template: `
    @if (data) {
      <div class="page">
        <h1>Search</h1>
        <p class="dek">Results for “{{ route.snapshot.queryParamMap.get('q') || '' }}”.</p>
        <section class="card stack">
          <h2>Courses</h2>
          @for (course of data.courses; track course.id) {
            <a [routerLink]="'/courses/' + course.slug">{{ course.title }}</a>
          }
          @if (!data.courses.length) {
            <p class="muted">No courses.</p>
          }
          <h2>People</h2>
          @for (person of data.people; track person.id) {
            <p>{{ person.full_name }} <span class="muted">{{ person.email }}</span></p>
          }
          @if (!data.people.length) {
            <p class="muted">No people.</p>
          }
          <h2>Resources</h2>
          @for (item of data.resources; track item.id) {
            <a routerLink="/library">{{ item.title }} <span class="muted">{{ item.kind }}</span></a>
          }
          @if (!data.resources.length) {
            <p class="muted">No resources.</p>
          }
          <h2>Groups</h2>
          @for (group of data.groups; track group.id) {
            <a [routerLink]="'/groups/' + group.id">{{ group.name }}</a>
          }
          @if (!data.groups.length) {
            <p class="muted">No groups.</p>
          }
        </section>
      </div>
    }
  `,
})
export class SearchComponent implements OnInit {
  api = inject(ApiService);
  route = inject(ActivatedRoute);
  private destroyRef = inject(DestroyRef);
  data: any = null;

  ngOnInit() {
    this.route.queryParamMap.pipe(takeUntilDestroyed(this.destroyRef)).subscribe(() => this.load());
  }

  async load() {
    const q = this.route.snapshot.queryParamMap.get('q') || '';
    this.data = await this.api.api(`/search?q=${encodeURIComponent(q)}`);
  }
}

// src/views/Search.vue
<script setup>
import { onMounted, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import { api } from '../api'

const route = useRoute()
const data = ref(null)

async function load() {
  data.value = await api(`/search?q=${encodeURIComponent(route.query.q || '')}`)
}
onMounted(load)
watch(() => route.query.q, load)
</script>

<template>
  <div v-if="data" class="page">
    <h1>Search</h1>
    <p class="dek">Results for “{{ route.query.q || '' }}”.</p>
    <section class="card stack">
      <h2>Courses</h2>
      <router-link v-for="course in data.courses" :key="course.id" :to="`/courses/${course.slug}`">{{ course.title }}</router-link>
      <p v-if="!data.courses.length" class="muted">No courses.</p>
      <h2>People</h2>
      <p v-for="person in data.people" :key="person.id">{{ person.full_name }} <span class="muted">{{ person.email }}</span></p>
      <p v-if="!data.people.length" class="muted">No people.</p>
      <h2>Resources</h2>
      <router-link v-for="item in data.resources" :key="item.id" to="/library">{{ item.title }} <span class="muted">{{ item.kind }}</span></router-link>
      <p v-if="!data.resources.length" class="muted">No resources.</p>
      <h2>Groups</h2>
      <router-link v-for="group in data.groups" :key="group.id" :to="`/groups/${group.id}`">{{ group.name }}</router-link>
      <p v-if="!data.groups.length" class="muted">No groups.</p>
    </section>
  </div>
</template>
